create table Users (
    ID bigint primary key generated by default as identity,
    NAME varchar(50),
    EMAIL varchar(100),
    IS_SEND boolean default false
);

alter table public.users replica identity full;